### PR TITLE
Adds subfactions-related database tables

### PR DESCRIPTION
**Pull request by sklarsa**
This is the first part to adding subfactions to the app.

I created a few tables:
- SubFactions
  - Contains SubFaction information including name and description (ability)
- MemberSubFactions
  - Mapping between team members and subfactions
  - NOTE: I needed to recreate the `Members` team, since SQLite does not support adding foreign keys to existing tables.
- ModelProfileSubFaction
  - Mapping between model profiles and possible subfaction selections (to be populated by the Rules database at a later date)

The migrations succeed, the app boots, and I performed the following actions:
1. Created/Deleted a team
2. Added a team member

Is there any other testing I should try?

### CODE REVIEW

**Comment by DevJonny** [comment]
Did you have an existing team before the changes were applied to the database? That's the only other test we'd need as people get real twitchy when their teams get deleted. As all old Teams won't have a subfaction to start off with, do they all still work?

**Comment by sklarsa** [comment]
I testing this with a factory reset.  Added some teams in develop, and then fired up the app on this branch.  All teams were accessible and I'm still able to perform basic CRUD actions like adding/deleting members, changing weapons configs, and adding/deleting teams.

Is it possible for you to confirm this as well as a sanity check?

**Comment by DevJonny** [comment]
Yeah I'll try and sanity check it later unless @jakemco or @lacombet can. I need to reinstall XCode again as I didn't have enough space to update my Mac!

**Comment by sklarsa** [comment]
Update on this: I'm still working on transcribing all of the subfaction copy into a local branch of KTRules to populate these tables.. I just haven't had the time to complete this

**Pull request closed without merging**
