### PR TITLE
Issue #85 Adds team points picker

### PR DESCRIPTION
**Pull request by sklarsa**
With preset options to choose 100, 125, or 200 points for Core, Elites, or Commander

### CODE REVIEW

**Comment by sklarsa** [comment]
Fixes https://github.com/KTManager/KTManagerApp/issues/85

**Review by DevJonny — COMMENTED** [review]
All looks good code wise. Don't have time to test it manually so I'll trust that you have :) 

The only thing I wanted to flag is that `KillTeam/Properties/Resources.Designer.cs` has been deleted. Was this intentional?

**Comment by sklarsa** [comment]
Oh oops, not sure how that got deleted. I’ll run some more testing myself later today

**Comment by sklarsa** [comment]
Looking now, it's just a large diff that was not rendered.  The file still exists

**Comment by sklarsa** [comment]
Updated with a bug fix, so newly created teams are set to 100 points by default.  Also internationalized text.

**Review by DevJonny — APPROVED** [review]

**Comment by DevJonny** [comment]
Looks good @sklarsa squash and merge when you're ready

**Comment by DevJonny** [comment]
> Looking now, it's just a large diff that was not rendered. The file still exists

Ah my bad, just saw the red bars but didn't load the diff.

**Comment by sklarsa** [comment]
```
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.
```

**Comment by DevJonny** [comment]
Done, thanks @sklarsa

**Pull request merged**
